In [1]:
import numpy as np

# Boolean Masking

In [2]:
mat = np.random.rand(10, 10)
mat

array([[0.68954913, 0.1172851 , 0.8048633 , 0.15896822, 0.09233382,
        0.65424989, 0.83233493, 0.39634735, 0.79660602, 0.38464376],
       [0.16656732, 0.83758431, 0.17313743, 0.89061402, 0.26485812,
        0.97350978, 0.6749181 , 0.45767756, 0.28059083, 0.16473434],
       [0.18974084, 0.98478961, 0.98224595, 0.7645109 , 0.38522895,
        0.95518618, 0.29312625, 0.34866539, 0.20881186, 0.48726183],
       [0.11744832, 0.26419349, 0.92112573, 0.44122471, 0.61695589,
        0.75568024, 0.71034986, 0.17260652, 0.37052516, 0.47915602],
       [0.88566437, 0.95156213, 0.69370172, 0.95314814, 0.82141595,
        0.95100821, 0.85353268, 0.13684557, 0.65823011, 0.24246108],
       [0.62452373, 0.83896088, 0.6980459 , 0.92280982, 0.61779942,
        0.41022812, 0.05789224, 0.66476402, 0.6490897 , 0.86499875],
       [0.10612065, 0.18642266, 0.06442416, 0.03341098, 0.50835296,
        0.87085978, 0.81290312, 0.6972192 , 0.08410471, 0.17373712],
       [0.73300208, 0.41021113, 0.5524330

In [3]:
# Checking out the properties
mat.mean()

0.5328505708210498

In [4]:
mat.std()

0.30008130437069414

In [5]:
# Checking the values that are greater than 1.5 standard deviations from the mean
mat[np.abs(mat - mat.mean()) > mat.std()]

array([0.1172851 , 0.15896822, 0.09233382, 0.16656732, 0.83758431,
       0.17313743, 0.89061402, 0.97350978, 0.16473434, 0.18974084,
       0.98478961, 0.98224595, 0.95518618, 0.20881186, 0.11744832,
       0.92112573, 0.17260652, 0.88566437, 0.95156213, 0.95314814,
       0.95100821, 0.85353268, 0.13684557, 0.83896088, 0.92280982,
       0.05789224, 0.86499875, 0.10612065, 0.18642266, 0.06442416,
       0.03341098, 0.87085978, 0.08410471, 0.17373712, 0.00924982,
       0.9476817 , 0.93005856, 0.10646363, 0.95603391, 0.97205069,
       0.21189546, 0.84804053, 0.0239686 , 0.1933734 , 0.05615989,
       0.182926  ])

In [6]:
# Checking how many values are above the mean
len(mat[mat > mat.mean()])

52

In [7]:
# Checking how many values are within one standard deviation
len(mat[np.abs(mat - mat.mean()) < mat.std()])

54

# Reading and dumping data

In [8]:
v = np.random.rand(5, 5)

In [9]:
v

array([[0.11401899, 0.31231286, 0.07759063, 0.04225   , 0.97983194],
       [0.06235511, 0.29262569, 0.52808776, 0.65664798, 0.00979352],
       [0.66604276, 0.32102129, 0.40187661, 0.64574219, 0.74333912],
       [0.51133342, 0.9169354 , 0.21633619, 0.83555209, 0.97152946],
       [0.87455479, 0.94878162, 0.81051046, 0.21489755, 0.05697943]])

In [11]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x05K\x05\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00f8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X-\x01\x00\x00h\xc2\xba\x08NY0\xc2\xbd?\x04\xc3\x94\xc3\xac\x10\xc3\xaf\xc3\xbc\xc3\x93?`\xc2\x9fA\xc3\x84\xc3\xba\xc3\x9c\xc2\xb3?\x102\x04\xc2\xa6\xc3\x8a\xc2\xa1\xc2\xa5?a:\xc2\x8e\xc2\x83\xc3\x88Z\xc3\xaf?0t/c\x02\xc3\xad\xc2\xaf?\x10\xc3\x8f\xc3\xa7\x19a\xc2\xba\xc3\x92?\xc3\xb3\xc3\xa1SL\x18\xc3\xa6\xc3\xa0?\xc3\x83A\xc3\x81\xc2\x9fB\x03\xc3\xa5?\x00\xc3\x8c*~\xc2\xa0\x0e\xc2\x84?m\xc2\xaa\xc2\xb3\xc3\xa68P\xc3\xa5?P\xc3\x8b\xc3\x86\xc3\x9d\xc2\x9c\xc2\x8b\xc3\x94?&"l\xc2\xafX\xc2\xb8\xc3\x99?\xc3\x9c_\x1c\xc2\x89\xc3\xab\xc2\xa9\xc3\xa4?\xc2\x8bU\x0e\x1eo\xc3\x89\xc3\xa7?G\xc3\x8e\xc3\x99\xc3\xa9\xc3\x97\\\xc3\xa0?i\x

In [18]:
import pickle
v2 = pickle.loads(data)

In [19]:
v2

array([[0.11401899, 0.31231286, 0.07759063, 0.04225   , 0.97983194],
       [0.06235511, 0.29262569, 0.52808776, 0.65664798, 0.00979352],
       [0.66604276, 0.32102129, 0.40187661, 0.64574219, 0.74333912],
       [0.51133342, 0.9169354 , 0.21633619, 0.83555209, 0.97152946],
       [0.87455479, 0.94878162, 0.81051046, 0.21489755, 0.05697943]])

In [20]:
type(data)

bytes

# Universal functions

If we wrote a program for the RELU function, we could pass in scalar values, but would receive an error when passing in an array.

In [34]:
v1 = np.arange(10)

In [22]:
def relu(x):
    if x < 0:
        return 0
    else:
        return x

In [23]:
relu(4)

4

In [24]:
relu(-4)

0

In [28]:
relu(v1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In this case, the any() or all() functions are not useful, as passing them in as arguments to RELU will only return True or False based on whether or not any or all of the values are zero. In this case, since any of the values returned are true, we will get true, but all of them will not, so all will get false.

We can use the numpy decorator _vectorize_ to allow our relu function to return values when given an array.

In [35]:
@np.vectorize
def relu(x):
    if x < 0:
        return 0
    else:
        return x

In [36]:
relu(4)

array(4)

In [37]:
relu(4).shape

()

Now, relu returns an array when a scalar is passed in. The shape returned is an empty tuple.

In [38]:
relu(v1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
relu(v1).shape

(10,)

In [40]:
nv = np.array([-1, np.nan, 1])
np.sin(nv)

array([-0.84147098,         nan,  0.84147098])

In [41]:
relu(nv)

ValueError: cannot convert float NaN to integer

The vectorized version of the function cannot handle nan values (although normal numpy functions will return nan when given nan. We need to adjust the function to handle nan values.

In [42]:
@np.vectorize
def relu(x):
    if not np.isnan(x) and x < 0:
        return 0
    else:
        return x

In [44]:
relu(nv)

ValueError: cannot convert float NaN to integer

Notice how this still does not work, because nan is a floating point number, and numpy created an integer array. To correct this, we will return the class 0, which can sometimes return floats or integers.

In [47]:
@np.vectorize
def relu(x):
    if not np.isnan(x) and x < 0:
        return x.__class__(0)
    else:
        return x

In [48]:
relu(nv)

array([ 0., nan,  1.])

In [56]:
@np.vectorize
def check(x):
    return not np.isnan(nv) and n < 0

In [59]:
nv[nv != np.isnan(nv)]

array([-1., nan,  1.])